# Generated by Django 3.1.6 on 2021-02-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darmankade_app', '0002_comment_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commets', to='darmankade_app.doctor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commets', to='darmankade_app.patient'),
        ),
        migrations.AlterField(
            model_name='star',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='darmankade_app.doctor'),
        ),
        migrations.AlterField(
            model_name='star',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='darmankade_app.patient'),
        ),
    ]
