# Generated by Django 2.2.5 on 2021-02-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darmankade_app', '0003_auto_20210207_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='darmankade_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='darmankade_app.Patient'),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
