# Generated by Django 3.1.6 on 2021-02-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darmankade_app', '0003_auto_20210211_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('ارتوپدی', 'ارتوپدی'), ('اورولوژی', 'اورولوژی'), ('پوست و مو', 'پوست و مو'), ('زنان و زایمان', 'زنان و زایمان'), ('داخلی', 'داخلی'), ('گوش، حلق و بینی', 'گوش، حلق و بینی'), ('مغز و اعصاب', 'مغز و اعصاب')], max_length=50),
        ),
    ]
